[build-system]
build-backend = 'mesonpy'
requires = [
  "meson>=1.1.0",
  "meson-python>=0.13.0",
  "ninja",
  "wheel",
  "setuptools",
  "pip>=23.0"
]

[project]
name = "OpenPIV-cxx"
version = "0.3.0"
description = "OpenPIV-cxx consists of Python and c++ modules to be used with OpenPIV-Python to help accelerate demanding processing pipelines."
readme = "README.md"
license = { text = "GPLv3" }
authors = [
  { name = "OpenPIV Contributors" }
]
keywords = ["PIV", "particle image velocimetry", "fluid mechanics"]
classifiers = [
  "Development Status :: 4 - Beta",

  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",

  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS",

  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Topic :: Scientific/Engineering"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest>=7.4.3"]

[tool.meson-python]
allow-windows-internal-shared-libs = true

[tool.meson-python.args]
setup = [
  "--wrap-mode=nodownload",
  "-Dbuild_wrapper=true",
  "-Ddisable_image_loaders=true",
  "-Dtests=false",
  "-Ddefault_library=shared"
]
install = ['--skip-subprojects=fmt']

[tool.meson-python.wheel]
exclude = [
  "{libdir_shared}/libduccfft.dll*",
  "{libdir_shared}/libopenpivcore.dll*",
  "{libdir_shared}/libduccfft*.dylib*",
  "{libdir_shared}/libopenpivcore*.dylib*",
  "{libdir_static}/libduccfft.dll*",
  "{libdir_static}/libopenpivcore.dll*",
]

[tool.cibuildwheel]
skip = ["*_i686", "*_ppc64le", "*_s390x", "*_universal2"]
test-command = "python -c \"from openpiv_cxx import pyopenpivcore as cpiv; assert cpiv.DUCCFFT_SIMD_BACKEND()\""

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair --analyze-existing-exes --add-path \"{project}/build-wheel/ducc_fft_disbatch;{project}/build-wheel/openpiv\" --strip -v -w {dest_dir} {wheel}"

[tool.cibuildwheel.windows.config-settings]
build-dir = "build-wheel"

[tool.cibuildwheel.macos]
repair-wheel-command = "DYLD_LIBRARY_PATH=\"{project}/build-wheel/ducc_fft_disbatch:{project}/build-wheel/openpiv\" delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.macos.config-settings]
build-dir = "build-wheel"
