name: Build wheels

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
    types: [opened, labeled, reopened, synchronize]

jobs:
  build_wheels:
    name: ${{ matrix.python }} ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'build_wheels') }}

    strategy:
      fail-fast: false
      matrix:
        python: ["cp310"]
        include:
          - os: ubuntu-22.04
            platform: manylinux_x86_64
          - os: ubuntu-22.04
            platform: musllinux_x86_64
          - os: ubuntu-22.04-arm
            platform: manylinux_aarch64
          - os: ubuntu-22.04-arm
            platform: musllinux_aarch64
          - os: macos-15-intel
            platform: macosx_x86_64
          - os: macos-14
            platform: macosx_arm64
          - os: windows-2022
            platform: win_amd64

    steps:
      - name: Checkout openpiv
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Setup MSVC (32-bit)
        if: ${{ matrix.buildplat[1] == 'win32' }}
        uses: bus1/cabuild/action/msdevshell@e22aba57d6e74891d059d66501b6b5aed8123c4d  # v1
        with:
          architecture: 'x86'

      - name: Configure Windows ARM64 compiler
        if: ${{ matrix.platform == 'win_arm64' }}
        shell: pwsh
        run: |
          "C:\Program Files\LLVM\bin" >> $env:GITHUB_PATH
          "CC=clang-cl" >> $env:GITHUB_ENV
          "CXX=clang-cl" >> $env:GITHUB_ENV

      - name: Add custom path (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        run: echo "$GITHUB_WORKSPACE/builddir/openpiv" >> "$GITHUB_PATH"

      - name: Add custom path (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          "$env:GITHUB_WORKSPACE\builddir\openpiv" >> $env:GITHUB_PATH

      - name: Build wheels
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform }}

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-${{ matrix.python }}-${{ matrix.platform }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
